name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flame: ^1.7.3
  url_launcher: ^6.0.2
  sqflite: ^2.3.0
  flutter_svg: ^2.0.10+1
  wheel_chooser: ^1.1.2
  go_router: ^14.2.1
  intl: ^0.19.0
  shared_preferences:
  async:
  sqflite_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: sqflite_aurora-0.5.0
      path: packages/sqflite/sqflite_aurora

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/icon.png"
  image_path_ios: "assets/icons/icon.png"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  adaptive_icon_background: "assets/icons/icon_background.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/pieces/
    - assets/images/small_pieces/
    - assets/images/icons/
    - assets/images/guide_boards/
