name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  flutter_svg: ^2.0.10+1
  wheel_chooser: ^1.1.2
  infinite_carousel: ^1.1.1
  sqflite_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: sqflite_aurora-0.5.0
      path: packages/sqflite/sqflite_aurora

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/pieces/
    - assets/images/small_pieces/
    - assets/images/icons/
    - assets/images/guide_boards/
