class GamePageConst {
  static String leftArrow = "assets/images/icons/left_tab_bar_icon.svg";
  static String leftBigArrow = "assets/images/icons/left_big_arrow_icon.svg";
  static String rightArrow = "assets/images/icons/right_tab_bar_icon.svg";
  static String menuIcon = "assets/images/icons/gridicons_menus.svg";
  static String lampIcon =  "assets/images/icons/lamp_icon.svg";
  static String startPos = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
  static List<String> listOfColumns = ["h", "g", "f", "e", "d", "c", "b", "a"];
  static String gameStatusEnemyMove = "Ход противника ";
  static String gameStatusOurMove = "Ваш ход";
  static String gameStatusWhiteMove = "Ход белых";
  static String gameStatusBlackMove = "Ход чёрных";
  static String gameStatusStalemate = "Пат (Ничья)";
  static String gameStatusDraw = "Ничья";
  static String gameStatusYouWin = "Вы выиграли!";
  static String gameStatusYouLose = "Вы проиграли";
  static String gameStatusBlackWin = "Выиграли чёрные";
  static String gameStatusWhiteWin = "Выиграли белые";
  static String gameEndText = "Закончить игру";
  static String gameContinueText = "Продолжить";
  static String continueGameText = "Продолжить игру";
  static String gameRestartText = "Перезапустить матч";
  static String gameGiveUpText = "Сдаться";
  static String gameBackModalHeader = "Сдаться?";
  static String gameResultWin = "Победа";
  static String gameResultLose = "Поражение";
  static String gameResultWinBlack = "Победа чёрных";
  static String gameResultWinWhite = "Победа белых";
}
