"""initial_game_move_rating_table

Revision ID: e3838b4d6371
Revises: ce154ef66241
Create Date: 2024-08-25 21:27:16.069197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3838b4d6371'
down_revision: Union[str, None] = 'ce154ef66241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chess_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=16), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=True),
    sa.Column('player_white_id', sa.Integer(), nullable=True),
    sa.Column('player_black_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['player_black_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_white_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('move_side', sa.String(length=5), nullable=False),
    sa.Column('move', sa.String(length=6), nullable=False),
    sa.Column('piece', sa.String(length=1), nullable=False),
    sa.Column('promotion', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    op.drop_table('games')
    op.drop_table('chess_ratings')
    # ### end Alembic commands ###
